config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  has_one :address, class_name: "Address", dependent: :destroy
  has_many :phones, class_name: "Phone", inverse_of: :contact, dependent: :destroy

  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
  validates :email, presence: true
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts, class_name: "Contact"
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :get_kinds_for_select, except: %i[ show destroy ]
  http_basic_authenticate_with name: "secret-user", password: "secret-password", only: :destroy

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact
      .order(:name)
      .page(params[:page])
      .per(15)
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
    if (@contact.address == nil)
      @contact.build_address
    end
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: t('Message.New.Success.Contact') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: t('Message.Edit.Success.Contact') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('Message.Delete.Success.Contact') }
      format.json { head :no_content }
    end
  end

  private
    def get_kinds_for_select
      @kinds = Kind.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact
      .includes("kind")
      .includes("phones")
      .includes("address")
      .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(
        :name,
        :email,
        :kind_id,
        :rmk,
        address_attributes: [:street, :city, :state, :id ],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind
      .all
      .page(params[:page])
      .per(5)
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy

    respond_to do |format|
      format.html { redirect_to kinds_url, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  ESTADOS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]

  def options_for_states(selection)
    options_for_select(ESTADOS, selection)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <section class="row mb-3">
    <% if contact.errors.any? %>
      <section id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> <%= t 'Message.Error.Contact' %></h2>
        <ul>
          <% contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </section>
    <% end %>
    <section class="col-6 mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </section>
    <section class="col-6 mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.text_field :email, class: "form-control" %>
    </section>
    <section class="col-6 mb-3">
      <%= form.label :kind, class: "form-label" %>
      <%= form.collection_select(:kind_id, @kinds, :id, :description, {}, {:class => "form-select"}) %>
    </section>
    <section id="phones" class="col-6 mb-3">
      <section class="mb-3">
        <%= link_to_add_association('Add Phone', form, :phones, 'data-association-insertion-method' => "after" ) %>
      </section>
      <%= form.fields_for :phones do |phone_form|%>
        <%= render "phone_fields", f: phone_form %>
      <% end %>
    </section>
    <%= form.fields_for :address do |address_form|%>
      <section class="col-6 mb-3">
        <%= address_form.label :address, class: "form-label" %>
        <%= address_form.text_field :street, class: "form-control" %>
      </section>
      <section class="col-6 mb-3">
        <%= address_form.label :city, class: "form-label" %>
        <%= address_form.text_field :city, class: "form-control" %>
      </section>
      <section class="col-6 mb-3">
        <%= address_form.label :state, class: "form-label" %>
        <%= address_form.select :state, options_for_states(@contact.address.state), {}, {:class => "form-select"} %>
      </section>
    <% end %>
    <section class="col-6 mb-3">
      <%= form.label :rmk, class: "form-label" %>
      <%= form.text_area :rmk, class: "form-control" %>
    </section>
  </section>
  <section class="actions row mb-3">
    <section class="col-2">
      <%= form.submit t("Nav.Menu-item.Send"), class: "btn btn-outline-info" %>
    </section>
    <% if action_name == 'edit'  %>
      <section class="col-2">
        <%= link_to t('Nav.Menu-item.Show'), @contact, class: "btn btn-outline-secondary" %>
      </section>
    <% end %>
    <section class="col-2">
      <%= link_to t('Nav.Menu-item.Back'), contacts_path, class: "btn btn-outline-warning" %>
    </section>
  </section>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields row col">
  <div class="col-6">
    <%= f.label :phone, class: "form-label" %>
  </div>
  <div class="col-6">
    <%= link_to_remove_association 'Remove', f %>
  </div>
  <%= f.text_field :phone, class: "form-control" %>
</div>

app/views/contacts/edit.html.erb
<h1><%= "#{t 'Main.Title.Editing'} #{Contact.model_name.human}"%></h1>

<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<section class="container-sm container-md container-lg row mb-3">
  <p id="notice"><%= notice %></p>
  <h2><%= Contact.model_name.human(count: 2) %></h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%=Contact.human_attribute_name("name")%></th>
        <th><%=Contact.human_attribute_name("email")%></th>
        <th><%=Contact.human_attribute_name("kind")%></th>
        <th><%=Contact.human_attribute_name("rmk")%></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.kind.description %></td>
          <td><%= contact.rmk %></td>
          <td><%= link_to t('Nav.Menu-item.Show'), contact, class: "btn btn-outline-info" %></td>
          <td><%= link_to t('Nav.Menu-item.Edit'), edit_contact_path(contact), class: "btn btn-outline-secondary" %></td>
          <td><%= link_to t('Nav.Menu-item.Destroy'), contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>
<section class="row mb-3">
  <p>
    <%= paginate @contacts %>
  </p>
</section>
<br>
<section class="row mb-3">
  <p>
    <%= link_to "#{t 'Nav.Menu-item.New'} #{Contact.model_name.human}" , new_contact_path, class: "btn btn-primary" %>
  </p>
</section>

app/views/contacts/new.html.erb
<h1><%= "#{t 'Nav.Menu-item.New'} #{Contact.model_name.human}"%></h1>

<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<section class="container-sm container-md container-lg row mb-3">
  <p id="notice">
    <%= notice %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("name") %>:</strong>
    <%= @contact.name %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("email") %>:</strong>
    <%= @contact.email %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("kind") %>:</strong>
    <%= @contact.kind.description %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("address") %>:</strong>
    <%= "#{@contact.address.street}, #{@contact.address.city}, #{@contact.address.state}" %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("phones") %>:</strong>
    <% @contact.phones.each do |phone| %>
      <p>
        <%= phone.phone %>
      </p>
    <% end %>
  </p>
  <p>
    <strong><%= Contact.human_attribute_name("rmk") %>:</strong>
    <p>
      <%= @contact.rmk %>
    </p>
  </p>
</section>
<section class="actions row mb-3">
  <div class="col-1">
    <%= link_to 'Edit', edit_contact_path(@contact), class: "btn btn-outline-secondary" %>
  </div>
  <div class="col-1">
    <%= link_to t('Nav.Menu-item.Back'), contacts_path, class: "btn btn-outline-secondary" %>
  </div>
</section>

app/views/home/index.html.erb
<main class="container">
  <section>
    <h1><%= t('Main.Welcome')%></h1>
    <ul class="nav flex-column">
      <li class="nav-item"><%= link_to Kind.model_name.human(count: 2), kinds_path, class: "nav-link active" %></li>
      <li class="nav-item"><%= link_to Contact.model_name.human(count: 2), contacts_path, class: "nav-link active" %></li>
    </ul>
  </section>
</main>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form| %>
  <section class="row mb-3">
    <% if kind.errors.any? %>
      <section id="error_explanation">
        <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>
        <ul>
          <% kind.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </section>
    <% end %>
    <section class="col-6 mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_field :description, class: "form-control" %>
    </section>
  </section>
  <section class="actions row mb-3">
    <section class="col-2">
      <%= form.submit t("Nav.Menu-item.Send"), class: "btn btn-outline-info" %>
    </section>
    <% if action_name == 'edit'  %>
      <section class="col-2">
        <%= link_to t('Nav.Menu-item.Show'), @kind, class: "btn btn-outline-secondary" %>
      </section>
    <% end %>
    <section class="col-2">
      <%= link_to t('Nav.Menu-item.Back'), kinds_path, class: "btn btn-outline-warning" %>
    </section>
  </section>
<% end %>

app/views/kinds/edit.html.erb
<h1><%= "#{t 'Main.Title.Editing'} #{Kind.model_name.human}"%></h1>

<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<section class="container-sm container-md container-lg row mb-3">
  <p id="notice"><%= notice %></p>
  <h1><%= Kind.model_name.human(count: 2) %></h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @kinds.each do |kind| %>
        <tr>
          <td><%= kind.description %></td>
          <td><%= link_to t('Nav.Menu-item.Show'), kind, class: "btn btn-outline-info" %></td>
          <td><%= link_to t('Nav.Menu-item.Edit'), edit_kind_path(kind), class: "btn btn-outline-secondary" %></td>
          <td><%= link_to t('Nav.Menu-item.Destroy'), kind, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>
<section class="row">
  <p>
    <%= paginate @kinds %>
  </p>
</section>
<br>
<section class="row mb-3">
  <p>
    <%= link_to "#{t 'Nav.Menu-item.New'} #{Kind.model_name.human}" , new_kind_path, class: "btn btn-primary" %>
  </p>
</section>

app/views/kinds/new.html.erb
<h1><%= "#{t 'Nav.Menu-item.New'} #{Kind.model_name.human}"%></h1>

<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<section class="container-sm container-md container-lg">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Description:</strong>
    <%= @kind.description %>
  </p>
</section>
<section class="actions row mb-3">
  <div class="col-1">
    <%= link_to 'Edit', edit_kind_path(@kind), class: "btn btn-outline-secondary" %>
  </div>
  <div class="col-1">
    <%= link_to t('Nav.Menu-item.Back'), kinds_path, class: "btn btn-outline-secondary" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller]  %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller] %>
  </head>
  <%= render partial:"/shared/header" %>
  <body>
    <main class="container-sm container-md container-lg">
      <%= yield %>
    </main>
  </body>
  <%= render partial:"/shared/footer" %>
</html>

app/views/shared/_footer.html.erb
<footer class="container-sm container-md container-lg">
  <nav class="row">
      <p><a href="#">Terms of Use</a> | <a href="#">Privacy Policy</a></p>
  </nav>
  <p>Copyright © <%= DateTime.now.year %> Ruby Course</p>
<footer/>

app/views/shared/_header.html.erb
<header class="container-sm container-md container-lg">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to(t('Main.Home'), root_path, class: "navbar-brand mb-0 h1") %>
    </div>
  </nav>
</header>